#!/bin/bash
#
# UNICORE WORKLOW
#
### BEGIN INIT INFO
# Provides:          unicore-workflow
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       UNICORE Worklow
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

NAME="UNICORE WORKFLOW"

#This must be equal to this file name
SERVICE=unicore-workflow
UNICORE_USER=unicore
START=/usr/sbin/unicore-workflow-start.sh
STOP=/usr/sbin/unicore-workflow-stop.sh
PIDDIR=/var/run/unicore
LASTPID=$PIDDIR/workflow.pid

# source defaults file
[ -f /etc/default/$SERVICE ] && . /etc/default/$SERVICE

# make sure PID directory exists and is writable
mkdir -p $PIDDIR
chown $UNICORE_USER $PIDDIR

start() {
        log_daemon_msg "Starting $NAME"
        start-stop-daemon --start --chuid $UNICORE_USER --exec "$START"
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch "/var/lock/$SERVICE"
        log_end_msg $RETVAL
        echo
        sleep 3
        # protect from OOM
        MYPID=$(cat $LASTPID)
        [ -e /proc/$MYPID/oom_adj ] && echo "-17" > /proc/$MYPID/oom_adj
        return $RETVAL
}

stop() {
         log_daemon_msg "Stopping $NAME"
         echo
         su $UNICORE_USER -p "$STOP"
         log_end_msg $?
         rm -f "/var/lock/$SERVICE"
         echo
}


status(){
         if [ -a "$LASTPID" ]; then
                 status_of_proc -p "$LASTPID" "$SERVICE"
         else
                 log_failure_msg "$SERVICE is not running"
         fi
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;
  restart)
	stop
	start
	;;
  force-reload)
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|force-reload|help}"
	exit 1
esac

exit $RETVAL
